# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GhIgnore < Formula
  desc ""
  homepage ""
  version "1.0.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/haijima/gh-ignore/releases/download/v1.0.1/gh-ignore-darwin-arm64"
      sha256 "212ee5cb6b8a833a222097ed385afdc05ad3ecc14dc1af3baf574635cdfb773d"

      def install
        bin.install "gh-ignore-darwin-arm64" => "gh-ignore"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/haijima/gh-ignore/releases/download/v1.0.1/gh-ignore-darwin-amd64"
      sha256 "40be3357402e42085b868d27e176b9052068aaa836710c3b32e9a82998179cfc"

      def install
        bin.install "gh-ignore-darwin-amd64" => "gh-ignore"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/haijima/gh-ignore/releases/download/v1.0.1/gh-ignore-linux-amd64"
      sha256 "1258212203aacf71260a3a67a010a6277f7f7247fff2fc72846b5f5c12df58d9"

      def install
        bin.install "gh-ignore-linux-amd64" => "gh-ignore"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/haijima/gh-ignore/releases/download/v1.0.1/gh-ignore-linux-arm64"
      sha256 "2a574715d5c0ba900f20237844880547b886c8683e3ab7d03498cc534ff9bcfe"

      def install
        bin.install "gh-ignore-linux-arm64" => "gh-ignore"
      end
    end
  end
end
