# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dstr < Formula
  desc "Examines data distribution"
  homepage "https://github.com/haijima/dstr"
  version "1.0.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/haijima/dstr/releases/download/v1.0.0/dstr-darwin-amd64.tar.gz"
      sha256 "04f8d8e060865363d661277c5334905a06cb63e95cd1af10317eab5d4f3b5885"

      def install
        bin.install "dstr"
      end
    end
    on_arm do
      url "https://github.com/haijima/dstr/releases/download/v1.0.0/dstr-darwin-arm64.tar.gz"
      sha256 "6c64aa9a2cbf0eb37e02313a5542f1e8e46ad1c8d9c958b856af8859c445f544"

      def install
        bin.install "dstr"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/haijima/dstr/releases/download/v1.0.0/dstr-linux-amd64.tar.gz"
        sha256 "67169eb8f339b679d3d0f5ba3b3d4effae54e7a8c6f3f0cd9e63e500636ab99a"

        def install
          bin.install "dstr"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/haijima/dstr/releases/download/v1.0.0/dstr-linux-arm64.tar.gz"
        sha256 "2c775bf4b4e03a060d1ec187adfaeacdb469dca8a8ac359a07006052f27b5307"

        def install
          bin.install "dstr"
        end
      end
    end
  end
end
