# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dstr < Formula
  desc "Examines data distribution"
  homepage "https://github.com/haijima/dstr"
  version "1.0.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/haijima/dstr/releases/download/v1.0.1/dstr-darwin-amd64.tar.gz"
      sha256 "dfb032cc6908ec6bc7dd16ee9687cdc86d612ac5ab5eb41835e534549ac02e80"

      def install
        bin.install "dstr"
      end
    end
    on_arm do
      url "https://github.com/haijima/dstr/releases/download/v1.0.1/dstr-darwin-arm64.tar.gz"
      sha256 "6560155eac8a293080a9646ab55de896f5e89960aa7a2166d39d1c1d8e7e3319"

      def install
        bin.install "dstr"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/haijima/dstr/releases/download/v1.0.1/dstr-linux-amd64.tar.gz"
        sha256 "2d32bb89de84a8827f73981fe54e92c33f53482def032094f77779283fc05c99"

        def install
          bin.install "dstr"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/haijima/dstr/releases/download/v1.0.1/dstr-linux-arm64.tar.gz"
        sha256 "c7bb61c0c1c7ce91aa47a399fe76d791965954682db4c803cf274c389077f4b0"

        def install
          bin.install "dstr"
        end
      end
    end
  end
end
