# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GhIgnore < Formula
  desc ""
  homepage "https://github.com/haijima/gh-ignore"
  version "1.0.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/haijima/gh-ignore/releases/download/v1.0.1/gh-ignore-darwin-arm64"
      sha256 "98ae073690398589565bc98ada75ed8b0192d05eef1eae053dfb14cc186dd21f"

      def install
        bin.install "gh-ignore-darwin-arm64" => "gh-ignore"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/haijima/gh-ignore/releases/download/v1.0.1/gh-ignore-darwin-amd64"
      sha256 "34a742658807130dd1b099889cd55e6938f29bec798b009766ca4f2351935819"

      def install
        bin.install "gh-ignore-darwin-amd64" => "gh-ignore"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/haijima/gh-ignore/releases/download/v1.0.1/gh-ignore-linux-amd64"
      sha256 "6f22cf7d2fd13d1042bd84108a956ad8cdc5fabbcfbc4298d072043ef0d773c7"

      def install
        bin.install "gh-ignore-linux-amd64" => "gh-ignore"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/haijima/gh-ignore/releases/download/v1.0.1/gh-ignore-linux-arm64"
      sha256 "8c336b350299f641c7d782201ef2fa08109f7dfdf13cf7512260cbd1225bac5f"

      def install
        bin.install "gh-ignore-linux-arm64" => "gh-ignore"
      end
    end
  end
end
