# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Scone < Formula
  desc "Analyzes SQL queries"
  homepage "https://github.com/haijima/scone"
  version "1.2.3"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/haijima/scone/releases/download/v1.2.3/scone-darwin-amd64.tar.gz"
      sha256 "d38d997b4eeef7a9d01d5fac431e87f8fa3e1b6dd331eefed86c2718f77c2506"

      def install
        bin.install "scone"
      end
    end
    on_arm do
      url "https://github.com/haijima/scone/releases/download/v1.2.3/scone-darwin-arm64.tar.gz"
      sha256 "800adf416cc8319a050c01e1cc70463ecf46cf8747cebfaf9f8a452de4022e7f"

      def install
        bin.install "scone"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/haijima/scone/releases/download/v1.2.3/scone-linux-amd64.tar.gz"
        sha256 "c3aa035ea6baacbcc21cfc324a98f20948c27721e55c0316bc17c982666a0460"

        def install
          bin.install "scone"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/haijima/scone/releases/download/v1.2.3/scone-linux-arm64.tar.gz"
        sha256 "03a3c7e21e47b304246034858b5010268876883ab3c00a646da6c7ead04afd3a"

        def install
          bin.install "scone"
        end
      end
    end
  end
end
