# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Spreadit < Formula
  desc "Writes CSV data to Google Sheets"
  homepage "https://github.com/haijima/spreadit"
  version "1.4.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/haijima/spreadit/releases/download/v1.4.0/spreadit-darwin-amd64.tar.gz"
      sha256 "c25a75893e509eeb60199fafa35e2564a052fec9d18d270e72983c2b78c92f1f"

      def install
        bin.install "spreadit"
      end
    end
    on_arm do
      url "https://github.com/haijima/spreadit/releases/download/v1.4.0/spreadit-darwin-arm64.tar.gz"
      sha256 "5b50de2008bc0f8871db66191ff7df40aba9e01ee630b6c5132d4decb0b86506"

      def install
        bin.install "spreadit"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/haijima/spreadit/releases/download/v1.4.0/spreadit-linux-amd64.tar.gz"
        sha256 "cb1a982f45d381d6e83ffdf2e9a873630541bcbac7baf3b21b96128163555bb9"

        def install
          bin.install "spreadit"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/haijima/spreadit/releases/download/v1.4.0/spreadit-linux-arm64.tar.gz"
        sha256 "1f2aa21575bf185e26a3edececb6b2418775eb3e7a2905a23801a53336603584"

        def install
          bin.install "spreadit"
        end
      end
    end
  end
end
