# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stool < Formula
  desc "Profiles access log"
  homepage "https://github.com/haijima/stool"
  version "1.20.2"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/haijima/stool/releases/download/v1.20.2/stool-darwin-amd64.tar.gz"
      sha256 "b6a4e8afb64de113b6c913ffa78b967c6e06e5743a6e99bba051c05181fae19f"

      def install
        bin.install "stool"
      end
    end
    on_arm do
      url "https://github.com/haijima/stool/releases/download/v1.20.2/stool-darwin-arm64.tar.gz"
      sha256 "26028b6fe5d5fab05145473beed01fcf33d723934e8e693d49a686fde0f97a2d"

      def install
        bin.install "stool"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/haijima/stool/releases/download/v1.20.2/stool-linux-amd64.tar.gz"
        sha256 "64510f83fbd72946a3d69d474cbe87090aa9eb73059ecf527cf32a10a89ccabe"

        def install
          bin.install "stool"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/haijima/stool/releases/download/v1.20.2/stool-linux-arm64.tar.gz"
        sha256 "2e270ec345b889397f2d5998954fea3563bf323d7c6cdb4b7f0c0da6fa4839fa"

        def install
          bin.install "stool"
        end
      end
    end
  end
end
